// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj6Z3mfJFaZs_Vc4uWIC2QsUmtDn0jX1c',
    appId: '1:181753217030:web:93ee79268b92687ee14387',
    messagingSenderId: '181753217030',
    projectId: 'flutter-end-project-3f9be',
    authDomain: 'flutter-end-project-3f9be.firebaseapp.com',
    storageBucket: 'flutter-end-project-3f9be.firebasestorage.app',
    measurementId: 'G-YDMLP3PC56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbBcLRwZS2FObPWFjHbiXt5aFOFBqlVXI',
    appId: '1:181753217030:android:805ad7545f1dd5f7e14387',
    messagingSenderId: '181753217030',
    projectId: 'flutter-end-project-3f9be',
    storageBucket: 'flutter-end-project-3f9be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbhtg8U7GdEBr5R9XlamQy0bWaoeY8Yjg',
    appId: '1:181753217030:ios:f893f38b66328cc4e14387',
    messagingSenderId: '181753217030',
    projectId: 'flutter-end-project-3f9be',
    storageBucket: 'flutter-end-project-3f9be.firebasestorage.app',
    iosBundleId: 'com.example.quanLyMuc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbhtg8U7GdEBr5R9XlamQy0bWaoeY8Yjg',
    appId: '1:181753217030:ios:f893f38b66328cc4e14387',
    messagingSenderId: '181753217030',
    projectId: 'flutter-end-project-3f9be',
    storageBucket: 'flutter-end-project-3f9be.firebasestorage.app',
    iosBundleId: 'com.example.quanLyMuc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj6Z3mfJFaZs_Vc4uWIC2QsUmtDn0jX1c',
    appId: '1:181753217030:web:227c657999e876c5e14387',
    messagingSenderId: '181753217030',
    projectId: 'flutter-end-project-3f9be',
    authDomain: 'flutter-end-project-3f9be.firebaseapp.com',
    storageBucket: 'flutter-end-project-3f9be.firebasestorage.app',
    measurementId: 'G-X9MM0WR5XF',
  );

}